import subprocess
import pandas as pd
import os

projects = {
    '12V_PD': '12V_PD/12V_PD.kicad_sch',
    'IMU_PCB': 'IMU_PCB/Microcontroller.kicad_sch',
    'MCU_PCB': 'MCU_PCB/MCU.kicad_sch',
    'PDB': 'PDB/Power_Distribution_PCB_PROVE.kicad_sch',
    'TELEM': 'TELEM/Microcontroller.kicad_sch'
}

all_dfs = []

# 1. Run KiBot on each project individually
for proj, sch in projects.items():
    print(f"Running KiBot for {proj}...")
    out_dir = f"bom_temp_{proj}"
    
    # Execute KiBot into a temporary folder for this project
    subprocess.run(["kibot", "-c", "config.kibot.yaml", "-e", sch, "-d", out_dir], check=True)
    
    # Read the output generated by config.kibot.yaml
    csv_file = os.path.join(out_dir, "multi_project_master_bom.csv")
    df = pd.read_csv(csv_file)
    df.columns = df.columns.str.strip()
    
    # Ensure missing Purchase Links don't break grouping
    if 'Purchase Link' in df.columns:
        df['Purchase Link'] = df['Purchase Link'].fillna('')
        
    # Rename KiBot's 'Total Qty' column to the current project's name
    df.rename(columns={'Total Qty': proj}, inplace=True)
    
    # --- THE FIX ---
    # Force the quantity column to be numeric. This turns KiBot's metadata strings into 'NaN'
    df[proj] = pd.to_numeric(df[proj], errors='coerce')
    # Drop the rows that became 'NaN' (these are the junk metadata rows)
    df = df.dropna(subset=[proj])
    # ---------------
    
    # Keep only the grouping keys, project quantity, and references
    cols = ['Value', 'Footprint', 'Purchase Link', proj, 'References']
    cols = [c for c in cols if c in df.columns] 
    
    all_dfs.append(df[cols])

# 2. Combine and aggregate the data
print("Merging data...")
combined = pd.concat(all_dfs, ignore_index=True)
group_keys = ['Value', 'Footprint', 'Purchase Link']

# Define how to combine the columns (Sum quantities, concatenate strings)
agg_funcs = {proj: 'sum' for proj in projects.keys()}
agg_funcs['References'] = lambda x: ', '.join(x.dropna().astype(str))

# Group everything together 
merged = combined.groupby(group_keys, dropna=False).agg(agg_funcs).reset_index()

# 3. Clean up the final matrix
for proj in projects.keys():
    merged[proj] = merged[proj].fillna(0).astype(int) # Replace empty project qtys with 0

# Insert the master Total Qty column right after the grouping keys
merged.insert(len(group_keys), 'Total Qty', merged[list(projects.keys())].sum(axis=1))

# Export
merged.to_csv("Master_BOM_Matrix.csv", index=False)
print("Success! Created 'Master_BOM_Matrix.csv'")
